services:
  - type: web
    name: fullstack-intern-task-api
    env: node
    plan: free
    buildCommand: "npm install && npm run init-db"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /opt/render/project/src/database.sqlite
